# site properties and page defaults
title: Mosaic Lab
subtitle: Reproductive Genetics and Epidemiology
description: We use large-scale genetic and register data to investigate the biological mechanisms and environmental factors behind pregnancy loss and other reproductive and perinatal outcomes. Our vision is to transform our collective knowledge of the fundamental dynamics of early development and improve molecular diagnostics. We are based at the Wallenberg Laboratory, Institute of Medicine at the University of Gothenburg.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: pol.sole.navais@gu.se
  orcid: 0000-0002-3326-266X
  google-scholar: UjCYAAAAJ
  github: psnavais
  
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
